# Generated by Django 4.2.2 on 2024-09-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportform',
            old_name='picture',
            new_name='image',
        ),
        migrations.AddField(
            model_name='reportform',
            name='processed_image',
            field=models.ImageField(default=1, upload_to='processed_image/'),
            preserve_default=False,
        ),
    ]
