# Generated by Django 4.2.2 on 2024-09-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_picture_reportform_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportform',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_image/'),
        ),
    ]
