# Generated by Django 4.2.2 on 2024-09-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reportform_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportform',
            name='avg_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
