# Generated by Django 4.2.2 on 2024-09-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reportform_avg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportform',
            name='user',
        ),
    ]
